import 'viral_models.dart';

final List<ViralMediaItem> staticViralDatabase = [
  const ViralMediaItem(
    id: "movie_1",
    title: "The Shawshank Redemption",
    description:
        "Two prisoners bond over decades, finding eventual redemption.",
    popularityScore: 2984300,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_2",
    title: "The Dark Knight",
    description: "Batman battles the Joker to save Gotham from chaos.",
    popularityScore: 2869000,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_3",
    title: "Inception",
    description: "Thieves plant an idea into a target's mind via dreams.",
    popularityScore: 2558800,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_4",
    title: "Fight Club",
    description: "An office worker starts an underground fighting ring.",
    popularityScore: 2318800,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_5",
    title: "Pulp Fiction",
    description:
        "Interconnected tales of mobsters and criminals in Los Angeles.",
    popularityScore: 2268900,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_6",
    title: "Forrest Gump",
    description:
        "A simple man unwittingly witnesses history's biggest moments.",
    popularityScore: 2258800,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_7",
    title: "The Matrix",
    description:
        "A hacker discovers reality is actually a computer simulation.",
    popularityScore: 2108700,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_8",
    title: "The Lord of the Rings: The Fellowship of the Ring",
    description: "A hobbit begins a journey to destroy a powerful ring.",
    popularityScore: 2058800,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_9",
    title: "The Godfather",
    description: "A reluctant son takes control of his father's crime empire.",
    popularityScore: 2049200,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_10",
    title: "Interstellar",
    description: "Astronauts travel through a wormhole to find a new home.",
    popularityScore: 2038600,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_11",
    title: "The Lord of the Rings: The Return of the King",
    description:
        "The final battle for Middle-earth begins as Frodo nears Mordor.",
    popularityScore: 1989000,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_12",
    title: "The Dark Knight Rises",
    description: "Batman returns from exile to save Gotham from Bane.",
    popularityScore: 1878400,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_13",
    title: "Se7en",
    description: "Detectives hunt a serial killer using the seven deadly sins.",
    popularityScore: 1828600,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_14",
    title: "The Lord of the Rings: The Two Towers",
    description: "The fellowship divides to fight Saruman's armies.",
    popularityScore: 1808700,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_15",
    title: "Django Unchained",
    description: "A freed slave rescues his wife from a brutal plantation.",
    popularityScore: 1728400,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_16",
    title: "Gladiator",
    description: "A betrayed general seeks revenge against a corrupt emperor.",
    popularityScore: 1658500,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_17",
    title: "Batman Begins",
    description: "Bruce Wayne trains to become Gotham's dark protector.",
    popularityScore: 1608200,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_18",
    title: "Inglourious Basterds",
    description: "Jewish soldiers plot to assassinate Nazi leaders in France.",
    popularityScore: 1588300,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_19",
    title: "The Silence of the Lambs",
    description: "A cadet seeks a cannibal's help to catch a killer.",
    popularityScore: 1568600,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_20",
    title: "Saving Private Ryan",
    description: "Soldiers go behind enemy lines to save a paratrooper.",
    popularityScore: 1528600,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_21",
    title: "The Wolf of Wall Street",
    description: "A stockbroker's rise and fall through corruption and excess.",
    popularityScore: 1518200,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_22",
    title: "Star Wars: Episode IV - A New Hope",
    description:
        "Luke Skywalker joins the rebellion against the Galactic Empire.",
    popularityScore: 1488600,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_23",
    title: "Joker",
    description: "A disregarded comedian descends into madness and crime.",
    popularityScore: 1478400,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_24",
    title: "Avengers: Infinity War",
    description:
        "Avengers fight to stop Thanos from destroying half the universe.",
    popularityScore: 1468400,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_25",
    title: "Avengers: Endgame",
    description:
        "The remaining Avengers assemble to reverse Thanos's destruction.",
    popularityScore: 1458400,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_26",
    title: "The Departed",
    description: "A cop and a mole infiltrate each other's organizations.",
    popularityScore: 1428500,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_27",
    title: "The Prestige",
    description: "Rival magicians battle to create the ultimate illusion.",
    popularityScore: 1418500,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_28",
    title: "The Green Mile",
    description: "Guards encounter a death row inmate with miraculous powers.",
    popularityScore: 1408600,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_29",
    title: "Shutter Island",
    description: "A marshal investigates a disappearance at a remote asylum.",
    popularityScore: 1398200,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_30",
    title: "Memento",
    description: "A man with short-term memory loss hunts his wife's killer.",
    popularityScore: 1358400,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_31",
    title: "Avatar",
    description: "A marine bonds with aliens on a distant planet.",
    popularityScore: 1347800,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_32",
    title: "The Empire Strikes Back",
    description: "Luke trains with Yoda while Vader pursues the rebels.",
    popularityScore: 1338700,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_33",
    title: "Back to the Future",
    description: "A teen travels back to 1955 in a DeLorean.",
    popularityScore: 1328500,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_34",
    title: "American Beauty",
    description: "A suburban father suffers a mid-life crisis.",
    popularityScore: 1288300,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_35",
    title: "Goodfellas",
    description: "The rise and fall of a mob associate over decades.",
    popularityScore: 1258700,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_36",
    title: "Titanic",
    description: "A romance blooms on the ill-fated ocean liner.",
    popularityScore: 1247800,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_37",
    title: "Léon: The Professional",
    description: "A professional hitman protects a 12-year-old girl.",
    popularityScore: 1238500,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_38",
    title: "V for Vendetta",
    description: "A masked vigilante fights a futuristic British tyranny.",
    popularityScore: 1218200,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_39",
    title: "American History X",
    description: "A reformed neo-Nazi tries to save his younger brother.",
    popularityScore: 1208500,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_40",
    title: "Pirates of the Caribbean: The Curse of the Black Pearl",
    description: "A blacksmith and a pirate save a kidnapped woman.",
    popularityScore: 1198000,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_41",
    title: "WALL·E",
    description: "A lonely robot travels to space to save humanity.",
    popularityScore: 1188400,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_42",
    title: "Kill Bill: Vol. 1",
    description: "An assassin seeks revenge on her former team.",
    popularityScore: 1178100,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_43",
    title: "Terminator 2: Judgment Day",
    description: "A cyborg protects a boy from a liquid metal killer.",
    popularityScore: 1168500,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_44",
    title: "The Usual Suspects",
    description: "A sole survivor narrates a heist gone wrong.",
    popularityScore: 1148500,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_45",
    title: "The Truman Show",
    description: "A man discovers his entire life is a TV show.",
    popularityScore: 1138100,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_46",
    title: "Iron Man",
    description: "A billionaire builds a high-tech suit to fight evil.",
    popularityScore: 1127900,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_47",
    title: "The Lion King",
    description: "A lion cub reclaims his throne from his evil uncle.",
    popularityScore: 1108500,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_48",
    title: "Star Wars: Episode VI - Return of the Jedi",
    description: "Rebels attack the second Death Star to defeat the Empire.",
    popularityScore: 1098300,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_49",
    title: "Finding Nemo",
    description: "A clownfish searches the ocean for his lost son.",
    popularityScore: 1088100,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_50",
    title: "Braveheart",
    description:
        "William Wallace leads a Scottish rebellion against English tyranny.",
    popularityScore: 1078300,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_51",
    title: "Up",
    description: "An old man flies his house to South America.",
    popularityScore: 1068200,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_52",
    title: "Reservoir Dogs",
    description: "Thieves suspect a mole after a botched jewelry heist.",
    popularityScore: 1058300,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_53",
    title: "Toy Story",
    description: "Toys come alive and rival for a boy's affection.",
    popularityScore: 1048300,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_54",
    title: "Raiders of the Lost Ark",
    description: "Indiana Jones races Nazis to find the Ark of the Covenant.",
    popularityScore: 1038400,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_55",
    title: "Good Will Hunting",
    description: "A janitor genius finds direction with a psychologist's help.",
    popularityScore: 1028300,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_56",
    title: "The Sixth Sense",
    description: "A boy who sees ghosts seeks a psychologist's help.",
    popularityScore: 1018100,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_57",
    title: "Eternal Sunshine of the Spotless Mind",
    description: "A couple erases memories of their relationship.",
    popularityScore: 1008300,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_58",
    title: "Deadpool",
    description: "A disfigured mercenary hunts the man who ruined his looks.",
    popularityScore: 998000,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_59",
    title: "Mad Max: Fury Road",
    description: "Rebels race across a wasteland to escape a tyrant.",
    popularityScore: 988100,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_60",
    title: "The Shining",
    description: "A family is terrorized by ghosts in an isolated hotel.",
    popularityScore: 978400,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_61",
    title: "Guardians of the Galaxy",
    description: "Space criminals unite to save the galaxy from a fanatic.",
    popularityScore: 968000,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_62",
    title: "Monsters, Inc.",
    description: "Monsters scare kids for energy until a child enters.",
    popularityScore: 958100,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_63",
    title: "Catch Me If You Can",
    description: "An FBI agent hunts a brilliant young con artist.",
    popularityScore: 948100,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_64",
    title: "No Country for Old Men",
    description: "A hunter finds drug money and is pursued by a killer.",
    popularityScore: 938100,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_65",
    title: "Gone Girl",
    description: "A man is suspected of causing his wife's disappearance.",
    popularityScore: 928100,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_66",
    title: "A Clockwork Orange",
    description:
        "A delinquent undergoes a state-sponsored behavior modification experiment.",
    popularityScore: 918300,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_67",
    title: "Alien",
    description: "A space crew is hunted by a deadly extraterrestrial.",
    popularityScore: 908400,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_68",
    title: "Schindler's List",
    description: "A German industrialist saves Jewish workers during WWII.",
    popularityScore: 899000,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_69",
    title: "Harry Potter and the Sorcerer's Stone",
    description: "An orphan enrolls in a school of wizardry.",
    popularityScore: 887600,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_70",
    title: "Die Hard",
    description: "A cop fights terrorists in a Los Angeles skyscraper.",
    popularityScore: 878200,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_71",
    title: "Jurassic Park",
    description: "Cloned dinosaurs escape confinement at a theme park.",
    popularityScore: 868100,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_72",
    title: "Whiplash",
    description: "A young drummer endures a ruthless music instructor.",
    popularityScore: 858500,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_73",
    title: "Snatch",
    description: "Criminals and promoters hunt for a stolen diamond.",
    popularityScore: 848300,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_74",
    title: "Gravity",
    description: "Two astronauts struggle to survive in deep space.",
    popularityScore: 837700,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_75",
    title: "Inside Out",
    description: "Emotions guide a young girl through life changes.",
    popularityScore: 828100,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_76",
    title: "Taxi Driver",
    description: "A stable cabbie descends into violence in NYC.",
    popularityScore: 818300,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_77",
    title: "Pan's Labyrinth",
    description: "A girl escapes war into a fantasy world.",
    popularityScore: 808200,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_78",
    title: "Star Wars: Episode VII - The Force Awakens",
    description: "New heroes search for Luke Skywalker to fight evil.",
    popularityScore: 797900,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_79",
    title: "Donnie Darko",
    description: "A troubled teen sees visions of a giant rabbit.",
    popularityScore: 788000,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_80",
    title: "Harry Potter and the Deathly Hallows: Part 2",
    description: "Harry faces Voldemort in a final battle for Hogwarts.",
    popularityScore: 778100,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_81",
    title: "Spider-Man",
    description: "A teen bitten by a spider fights crime in NYC.",
    popularityScore: 767300,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_82",
    title: "12 Angry Men",
    description: "A juror tries to convince others of a defendant's innocence.",
    popularityScore: 759000,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_83",
    title: "The Intouchables",
    description: "A wealthy quadriplegic hires a caregiver from the projects.",
    popularityScore: 748500,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_84",
    title: "District 9",
    description: "An agent is exposed to alien biotechnology in slums.",
    popularityScore: 737900,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_85",
    title: "Parasite",
    description: "A poor family infiltrates a wealthy household.",
    popularityScore: 728600,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_86",
    title: "Coco",
    description: "A boy enters the Land of the Dead to find music.",
    popularityScore: 718400,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_87",
    title: "Slumdog Millionaire",
    description: "A teen recalls his life during a game show.",
    popularityScore: 708000,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_88",
    title: "The Avengers",
    description: "Superheroes team up to stop an alien invasion.",
    popularityScore: 698000,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_89",
    title: "Prisoners",
    description: "A father hunts for his missing daughter.",
    popularityScore: 688100,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_90",
    title: "Black Swan",
    description: "A ballerina loses her grip on reality.",
    popularityScore: 678000,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_91",
    title: "Aliens",
    description: "Ripley returns to fight a colony of aliens.",
    popularityScore: 668300,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_92",
    title: "One Flew Over the Cuckoo's Nest",
    description: "A criminal leads a rebellion in a mental ward.",
    popularityScore: 658700,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_93",
    title: "Spider-Man: No Way Home",
    description: "Spider-Man faces villains from the multiverse.",
    popularityScore: 648300,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_94",
    title: "Oldboy",
    description: "A man seeks revenge after 15 years of imprisonment.",
    popularityScore: 638400,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_95",
    title: "Blade Runner",
    description: "A hunter tracks rogue androids in a cyberpunk future.",
    popularityScore: 628100,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_96",
    title: "Gran Torino",
    description: "A grumpy veteran befriends a Hmong teenager.",
    popularityScore: 618100,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_97",
    title: "Casino Royale",
    description: "Bond plays high-stakes poker to stop a terrorist.",
    popularityScore: 608000,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_98",
    title: "How to Train Your Dragon",
    description: "A viking befriends a dragon instead of killing it.",
    popularityScore: 598100,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_99",
    title: "Trainspotting",
    description: "A drug addict tries to clean up his life.",
    popularityScore: 588100,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "movie_100",
    title: "Into the Wild",
    description: "A graduate abandons society to live in Alaska.",
    popularityScore: 578100,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.movie,
  ),
  // 🎬 MOVIES — VIRAL
  // 🎮 GAMES — VIRAL
  // --- TIER 1: THE GOD TIER (Score: 900 - 1000) ---
  // const ViralMediaItem(
  //   id: "game_1",
  //   title: "Grand Theft Auto V",
  //   description: "The biggest open-world crime sandbox in history.",
  //   popularityScore: 998,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_2",
  //   title: "Minecraft",
  //   description: "Infinite creativity in a block-based survival world.",
  //   popularityScore: 995,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_3",
  //   title: "Red Dead Redemption 2",
  //   description: "A hyper-realistic outlaw epic set in the dying Wild West.",
  //   popularityScore: 990,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_4",
  //   title: "The Witcher 3: Wild Hunt",
  //   description: "The definitive open-world RPG about a monster slayer.",
  //   popularityScore: 985,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_5",
  //   title: "The Last of Us Part I",
  //   description: "An emotional journey across a post-pandemic America.",
  //   popularityScore: 980,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_6",
  //   title: "God of War (2018)",
  //   description: "Kratos returns as a father in the harsh Norse realm.",
  //   popularityScore: 975,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_7",
  //   title: "Elden Ring",
  //   description: "A challenging, dark fantasy open world by FromSoftware.",
  //   popularityScore: 972,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_8",
  //   title: "Baldur's Gate 3",
  //   description: "A massive D&D RPG with limitless player freedom.",
  //   popularityScore: 968,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_9",
  //   title: "The Last of Us Part II",
  //   description: "A brutal, divisive, and technically flawless revenge tale.",
  //   popularityScore: 965,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_10",
  //   title: "Cyberpunk 2077",
  //   description: "A futuristic RPG set in the neon-soaked Night City.",
  //   popularityScore: 960,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),

  // // --- TIER 2: THE LEGENDS (Score: 800 - 900) ---
  // const ViralMediaItem(
  //   id: "game_11",
  //   title: "Uncharted 4: A Thief's End",
  //   description: "Nathan Drake's final and most cinematic treasure hunt.",
  //   popularityScore: 955,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_12",
  //   title: "Skyrim (The Elder Scrolls V)",
  //   description: "The dragon-slaying RPG that defined a generation.",
  //   popularityScore: 950,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_13",
  //   title: "The Legend of Zelda: Breath of the Wild",
  //   description: "Nintendo's masterpiece of open-air exploration.",
  //   popularityScore: 948,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_14",
  //   title: "Ghost of Tsushima",
  //   description: "A samurai's beautiful and bloody fight for his homeland.",
  //   popularityScore: 945,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_15",
  //   title: "God of War Ragnarök",
  //   description: "The epic conclusion to the Norse saga.",
  //   popularityScore: 942,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_16",
  //   title: "Marvel's Spider-Man",
  //   description: "The ultimate superhero simulator in New York City.",
  //   popularityScore: 940,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_17",
  //   title: "Batman: Arkham City",
  //   description: "The Dark Knight fights to survive in a prison city.",
  //   popularityScore: 938,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_18",
  //   title: "Mass Effect 2",
  //   description:
  //       "Commander Shepard assembles a suicide squad to save humanity.",
  //   popularityScore: 935,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_19",
  //   title: "Portal 2",
  //   description: "A hilarious, mind-bending first-person puzzle game.",
  //   popularityScore: 930,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_20",
  //   title: "BioShock",
  //   description: "A shooter set in a terrifying underwater utopia.",
  //   popularityScore: 925,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_21",
  //   title: "Dark Souls III",
  //   description: "The polished finale to the punishing Dark Souls trilogy.",
  //   popularityScore: 920,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_22",
  //   title: "Horizon Zero Dawn",
  //   description: "Hunting robot dinosaurs in a lush post-apocalypse.",
  //   popularityScore: 915,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_23",
  //   title: "Grand Theft Auto: San Andreas",
  //   description: "The classic 90s gangsta rap saga of CJ.",
  //   popularityScore: 910,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_24",
  //   title: "Call of Duty: Modern Warfare 2 (2009)",
  //   description: "The peak of arcade military shooters.",
  //   popularityScore: 905,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_25",
  //   title: "Resident Evil 4 (Remake)",
  //   description: "Leon Kennedy saves the President's daughter from cultists.",
  //   popularityScore: 900,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),

  // // --- TIER 3: THE HITS (Score: 700 - 800) ---
  // const ViralMediaItem(
  //   id: "game_26",
  //   title: "Bloodborne",
  //   description: "Lovecraftian horror meets fast-paced action combat.",
  //   popularityScore: 895,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_27",
  //   title: "Fallout: New Vegas",
  //   description: "The fan-favorite RPG set in a nuclear Mojave desert.",
  //   popularityScore: 890,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_28",
  //   title: "Sekiro: Shadows Die Twice",
  //   description: "A ninja action game focused on precision parrying.",
  //   popularityScore: 885,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_29",
  //   title: "Hades",
  //   description: "Escape hell in this addictive rogue-like dungeon crawler.",
  //   popularityScore: 880,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_30",
  //   title: "Detroit: Become Human",
  //   description: "A branching narrative about androids gaining sentience.",
  //   popularityScore: 875,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_31",
  //   title: "Overwatch",
  //   description: "The hero shooter that defined a genre.",
  //   popularityScore: 870,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_32",
  //   title: "Counter-Strike: Global Offensive",
  //   description: "The ultimate competitive tactical shooter.",
  //   popularityScore: 868,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_33",
  //   title: "Metal Gear Solid V: The Phantom Pain",
  //   description: "Tactical espionage in a massive open world sandbox.",
  //   popularityScore: 865,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_34",
  //   title: "Uncharted 2: Among Thieves",
  //   description: "The game that put cinematic action on the map.",
  //   popularityScore: 860,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_35",
  //   title: "Final Fantasy VII Remake",
  //   description: "A modern reimagining of the classic RPG story.",
  //   popularityScore: 855,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_36",
  //   title: "Persona 5 Royal",
  //   description: "A stylish JRPG about teenage phantom thieves.",
  //   popularityScore: 850,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_37",
  //   title: "Doom Eternal",
  //   description: "Fast, brutal, and rhythmic demon slaying.",
  //   popularityScore: 845,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_38",
  //   title: "Star Wars Jedi: Fallen Order",
  //   description: "A Jedi survivor fights back against the Empire.",
  //   popularityScore: 840,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_39",
  //   title: "Assassin's Creed II",
  //   description: "Ezio's revenge tale in Renaissance Italy.",
  //   popularityScore: 835,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_40",
  //   title: "Hollow Knight",
  //   description: "A beautiful, melancholic, and difficult insect kingdom.",
  //   popularityScore: 830,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_41",
  //   title: "Destiny 2",
  //   description: "A massive online sci-fi shooter looter.",
  //   popularityScore: 825,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_42",
  //   title: "Apex Legends",
  //   description: "Fast-paced battle royale with unique character abilities.",
  //   popularityScore: 820,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_43",
  //   title: "PUBG: BATTLEGROUNDS",
  //   description: "The battle royale that started the craze.",
  //   popularityScore: 815,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_44",
  //   title: "Half-Life 2",
  //   description: "A physics-based revolution in first-person gaming.",
  //   popularityScore: 810,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_45",
  //   title: "NieR: Automata",
  //   description: "Androids fight a proxy war in a philosophical RPG.",
  //   popularityScore: 805,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_46",
  //   title: "Dota 2",
  //   description: "The deeply complex and competitive MOBA.",
  //   popularityScore: 800,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_47",
  //   title: "League of Legends",
  //   description: "The most popular esport in the world.",
  //   popularityScore: 795,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_48",
  //   title: "Fortnite",
  //   description: "A cultural phenomenon mixing shooting and building.",
  //   popularityScore: 790,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_49",
  //   title: "Genshin Impact",
  //   description: "A massive open-world anime RPG.",
  //   popularityScore: 785,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_50",
  //   title: "Fallout 4",
  //   description: "Scavenging and base-building in the Boston wasteland.",
  //   popularityScore: 780,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),

  // // --- TIER 4: THE CLASSICS & CULT HITS (Score: 600 - 700) ---
  // const ViralMediaItem(
  //   id: "game_51",
  //   title: "Terraria",
  //   description: "2D sandbox adventure with endless crafting.",
  //   popularityScore: 775,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_52",
  //   title: "Stardew Valley",
  //   description: "A relaxing farming simulator with heart.",
  //   popularityScore: 770,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_53",
  //   title: "Among Us",
  //   description: "A social deduction game about finding the imposter.",
  //   popularityScore: 765,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_54",
  //   title: "Team Fortress 2",
  //   description: "The timeless class-based cartoon shooter.",
  //   popularityScore: 760,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_55",
  //   title: "Rocket League",
  //   description: "Soccer played with rocket-powered cars.",
  //   popularityScore: 755,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_56",
  //   title: "Tom Clancy's Rainbow Six Siege",
  //   description: "Highly destructible tactical team combat.",
  //   popularityScore: 750,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_57",
  //   title: "Valorant",
  //   description: "Precise tactical shooting meets character abilities.",
  //   popularityScore: 745,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_58",
  //   title: "Rust",
  //   description: "Brutal multiplayer survival where trust is rare.",
  //   popularityScore: 740,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_59",
  //   title: "Dead by Daylight",
  //   description: "One killer hunts four survivors in this horror game.",
  //   popularityScore: 735,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_60",
  //   title: "Left 4 Dead 2",
  //   description: "The definitive co-op zombie shooter.",
  //   popularityScore: 730,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_61",
  //   title: "Undertale",
  //   description: "An RPG where you don't have to kill anyone.",
  //   popularityScore: 725,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_62",
  //   title: "Super Smash Bros. Ultimate",
  //   description: "The biggest crossover fighting game in history.",
  //   popularityScore: 720,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_63",
  //   title: "Mario Kart 8 Deluxe",
  //   description: "The essential kart racer for everyone.",
  //   popularityScore: 715,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_64",
  //   title: "Animal Crossing: New Horizons",
  //   description: "Build your perfect island paradise.",
  //   popularityScore: 710,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_65",
  //   title: "Pokémon GO",
  //   description: "Catch Pokémon in the real world.",
  //   popularityScore: 705,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_66",
  //   title: "Roblox",
  //   description: "A platform where users create their own games.",
  //   popularityScore: 700,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_67",
  //   title: "It Takes Two",
  //   description: "A genre-bending co-op adventure about marriage.",
  //   popularityScore: 695,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_68",
  //   title: "Cuphead",
  //   description: "A brutally hard run-and-gun with 1930s cartoon art.",
  //   popularityScore: 690,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_69",
  //   title: "Control",
  //   description: "Telekinetic combat in a shifting paranormal office.",
  //   popularityScore: 685,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_70",
  //   title: "Subnautica",
  //   description: "Terror and wonder in an alien ocean.",
  //   popularityScore: 680,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_71",
  //   title: "Valheim",
  //   description: "Viking survival with friends.",
  //   popularityScore: 675,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_72",
  //   title: "Disco Elysium",
  //   description: "A detective RPG driven by dialogue and internal monologue.",
  //   popularityScore: 670,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_73",
  //   title: "The Legend of Zelda: Ocarina of Time",
  //   description: "The N64 classic that defined 3D gaming.",
  //   popularityScore: 665,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_74",
  //   title: "Super Mario 64",
  //   description: "The first true 3D platforming adventure.",
  //   popularityScore: 660,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_75",
  //   title: "Metal Gear Solid",
  //   description: "The cinematic stealth game that started it all.",
  //   popularityScore: 655,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),

  // // --- TIER 5: THE ESSENTIALS (Score: 400 - 600) ---
  // const ViralMediaItem(
  //   id: "game_76",
  //   title: "Final Fantasy X",
  //   description: "A heartbreaking pilgrimage in the world of Spira.",
  //   popularityScore: 650,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_77",
  //   title: "Kingdom Hearts II",
  //   description: "Disney meets Final Fantasy in an action RPG.",
  //   popularityScore: 645,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_78",
  //   title: "Shadow of the Colossus",
  //   description: "Slaying giant beasts in a desolate land.",
  //   popularityScore: 640,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_79",
  //   title: "Silent Hill 2",
  //   description: "Psychological horror in a fog-covered town.",
  //   popularityScore: 635,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_80",
  //   title: "Resident Evil 2 (Remake)",
  //   description: "Surviving the Raccoon City police station.",
  //   popularityScore: 630,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_81",
  //   title: "Devil May Cry 5",
  //   description: "Stylish, high-octane demon hunting action.",
  //   popularityScore: 625,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_82",
  //   title: "Monster Hunter: World",
  //   description: "Tracking and slaying massive beasts.",
  //   popularityScore: 620,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_83",
  //   title: "Borderlands 2",
  //   description: "The chaotic looter-shooter with a villain you love to hate.",
  //   popularityScore: 615,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_84",
  //   title: "Divinity: Original Sin 2",
  //   description: "A deep tactical RPG with elemental combat.",
  //   popularityScore: 610,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_85",
  //   title: "Outer Wilds",
  //   description: "A space exploration mystery caught in a time loop.",
  //   popularityScore: 605,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_86",
  //   title: "Celeste",
  //   description: "A challenging platformer about overcoming anxiety.",
  //   popularityScore: 600,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_87",
  //   title: "Journey",
  //   description: "A silent, artistic voyage through a desert.",
  //   popularityScore: 595,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_88",
  //   title: "Limbo",
  //   description: "A dark, monochromatic puzzle-platformer.",
  //   popularityScore: 590,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_89",
  //   title: "Inside",
  //   description: "A disturbing dystopian puzzle adventure.",
  //   popularityScore: 585,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_90",
  //   title: "Batman: Arkham Asylum",
  //   description: "The game that redefined superhero combat.",
  //   popularityScore: 580,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_91",
  //   title: "Star Wars: Knights of the Old Republic",
  //   description: "The legendary Star Wars RPG twist.",
  //   popularityScore: 575,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_92",
  //   title: "Dragon Age: Origins",
  //   description: "A dark fantasy RPG where choices matter.",
  //   popularityScore: 570,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_93",
  //   title: "Civilization VI",
  //   description: "Build an empire to stand the test of time.",
  //   popularityScore: 565,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_94",
  //   title: "XCOM 2",
  //   description: "Turn-based tactical combat against alien overlords.",
  //   popularityScore: 560,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_95",
  //   title: "Slay the Spire",
  //   description: "The definitive deck-building roguelike.",
  //   popularityScore: 555,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_96",
  //   title: "Factorio",
  //   description: "Build and automate massive industrial factories.",
  //   popularityScore: 550,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_97",
  //   title: "RimWorld",
  //   description: "A sci-fi colony sim driven by AI storytellers.",
  //   popularityScore: 545,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_98",
  //   title: "Deep Rock Galactic",
  //   description: "Space dwarves mining and shooting bugs together.",
  //   popularityScore: 540,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_99",
  //   title: "Vampire Survivors",
  //   description: "A simple yet addictive gothic survival game.",
  //   popularityScore: 535,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // const ViralMediaItem(
  //   id: "game_100",
  //   title: "Tetris",
  //   description: "The perfect puzzle game.",
  //   popularityScore: 530,
  //   isFake: false,
  //   source: MediaSourceType.staticData,
  //   category: MediaCategory.game,
  // ),
  // 🎮 GAMES — VIRAL
  // SCALE: 2,000,000+ = Global Phenomenon (Matches Top Tier Movies)

  // --- TIER 1: THE TITANS (2.5M+) ---
  const ViralMediaItem(
    id: "game_1",
    title: "Minecraft",
    description: "The best-selling game of all time. Infinite creativity.",
    popularityScore:
        3000000, // #1 Game vs #1 Movie (Shawshank) is a close fight
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.game,
  ),
  const ViralMediaItem(
    id: "game_2",
    title: "Grand Theft Auto V",
    description: "The most profitable entertainment product ever made.",
    popularityScore: 2950000,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.game,
  ),
  const ViralMediaItem(
    id: "game_3",
    title: "Tetris",
    description: "The puzzle game that everyone on Earth recognizes.",
    popularityScore: 2800000, // Justice for Tetris
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.game,
  ),
  const ViralMediaItem(
    id: "game_4",
    title: "Fortnite",
    description: "More than a game. A cultural metaverse event.",
    popularityScore: 2750000,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.game,
  ),
  const ViralMediaItem(
    id: "game_5",
    title: "League of Legends",
    description: "The biggest esport in the world.",
    popularityScore: 2600000,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.game,
  ),

  // --- TIER 2: HOUSEHOLD NAMES (2.0M - 2.5M) ---
  const ViralMediaItem(
    id: "game_6",
    title: "Wii Sports",
    description: "The game that got your grandma playing bowling.",
    popularityScore: 2500000,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.game,
  ),
  const ViralMediaItem(
    id: "game_7",
    title: "Super Mario Bros.",
    description: "The platformer that saved the video game industry.",
    popularityScore: 2450000,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.game,
  ),
  const ViralMediaItem(
    id: "game_8",
    title: "PUBG: BATTLEGROUNDS",
    description: "The battle royale that started the global craze.",
    popularityScore: 2400000,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.game,
  ),
  const ViralMediaItem(
    id: "game_9",
    title: "Pokémon GO",
    description: "In 2016, this game brought world peace for one month.",
    popularityScore: 2350000, // Massive viral peak
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.game,
  ),
  const ViralMediaItem(
    id: "game_10",
    title: "Mario Kart 8 Deluxe",
    description: "The essential racing game. Ruins friendships.",
    popularityScore: 2300000,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.game,
  ),

  // --- TIER 3: BLOCKBUSTERS (1.5M - 2.0M) ---
  const ViralMediaItem(
    id: "game_11",
    title: "Red Dead Redemption 2",
    description: "A hyper-realistic outlaw epic set in the dying Wild West.",
    popularityScore: 2100000,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.game,
  ),
  const ViralMediaItem(
    id: "game_12",
    title: "The Witcher 3: Wild Hunt",
    description: "The definitive open-world RPG about a monster slayer.",
    popularityScore: 2050000,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.game,
  ),
  const ViralMediaItem(
    id: "game_13",
    title: "Skyrim (The Elder Scrolls V)",
    description: "The dragon-slaying RPG released on every device ever.",
    popularityScore: 2000000,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.game,
  ),
  const ViralMediaItem(
    id: "game_14",
    title: "Among Us",
    description: "A social deduction game about finding the imposter.",
    popularityScore: 1950000, // 2020 Viral giant
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.game,
  ),
  const ViralMediaItem(
    id: "game_15",
    title: "Call of Duty: Modern Warfare 2",
    description: "The peak of arcade military shooters and toxicity.",
    popularityScore: 1900000,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.game,
  ),
  const ViralMediaItem(
    id: "game_16",
    title: "Animal Crossing: New Horizons",
    description: "The cozy island simulator that saved us during lockdown.",
    popularityScore: 1850000,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.game,
  ),
  const ViralMediaItem(
    id: "game_17",
    title: "The Legend of Zelda: Breath of the Wild",
    description: "Nintendo's masterpiece of open-air exploration.",
    popularityScore: 1800000,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.game,
  ),
  const ViralMediaItem(
    id: "game_18",
    title: "The Last of Us Part I",
    description: "An emotional journey across a post-pandemic America.",
    popularityScore: 1750000,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.game,
  ),
  const ViralMediaItem(
    id: "game_19",
    title: "God of War (2018)",
    description: "Kratos returns as a father in the harsh Norse realm.",
    popularityScore: 1700000,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.game,
  ),
  const ViralMediaItem(
    id: "game_20",
    title: "Elden Ring",
    description: "A punishing open world masterpiece.",
    popularityScore: 1650000,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.game,
  ),

  // --- TIER 4: CRITICAL HITS & CULT CLASSICS (1.0M - 1.5M) ---
  const ViralMediaItem(
    id: "game_21",
    title: "Cyberpunk 2077",
    description: "A buggy launch, a legendary anime, a massive comeback.",
    popularityScore: 1600000,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.game,
  ),
  const ViralMediaItem(
    id: "game_22",
    title: "Baldur's Gate 3",
    description: "A massive D&D RPG with limitless player freedom.",
    popularityScore: 1550000,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.game,
  ),
  const ViralMediaItem(
    id: "game_23",
    title: "Overwatch",
    description: "The hero shooter that defined a genre.",
    popularityScore: 1500000,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.game,
  ),
  const ViralMediaItem(
    id: "game_24",
    title: "Portal 2",
    description: "A hilarious, mind-bending first-person puzzle game.",
    popularityScore: 1450000,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.game,
  ),
  const ViralMediaItem(
    id: "game_25",
    title: "Stardew Valley",
    description: "One man created the ultimate farming simulator.",
    popularityScore: 1400000,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.game,
  ),
  const ViralMediaItem(
    id: "game_26",
    title: "Dark Souls III",
    description: "The polished finale to the punishing trilogy.",
    popularityScore: 1350000,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.game,
  ),
  const ViralMediaItem(
    id: "game_27",
    title: "Hades",
    description: "Escape hell in this addictive rogue-like.",
    popularityScore: 1300000,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.game,
  ),
  const ViralMediaItem(
    id: "game_28",
    title: "Undertale",
    description: "An RPG where you don't have to kill anyone.",
    popularityScore: 1250000,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.game,
  ),
  const ViralMediaItem(
    id: "game_29",
    title: "Resident Evil 4 (Remake)",
    description: "Leon Kennedy vs Spanish cultists.",
    popularityScore: 1200000,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.game,
  ),
  const ViralMediaItem(
    id: "game_30",
    title: "Fallout: New Vegas",
    description: "The fan-favorite RPG set in a nuclear Mojave desert.",
    popularityScore: 1150000,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.game,
  ),

  // --- TIER 5: THE REST (Still 1M+ to beat obscure movies) ---
  const ViralMediaItem(
    id: "game_31",
    title: "Persona 5 Royal",
    description: "Teenage phantom thieves steal hearts.",
    popularityScore: 1100000,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.game,
  ),
  const ViralMediaItem(
    id: "game_32",
    title: "Bloodborne",
    description: "Lovecraftian horror meets fast action.",
    popularityScore: 1050000,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.game,
  ),
  const ViralMediaItem(
    id: "game_33",
    title: "Sekiro: Shadows Die Twice",
    description: "Hesitation is defeat.",
    popularityScore: 1000000,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.game,
  ),
  const ViralMediaItem(
    id: "game_34",
    title: "Detroit: Become Human",
    description: "A narrative game about android rights.",
    popularityScore: 950000, // Corrected: Lower than major hits
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.game,
  ),
  const ViralMediaItem(
    id: "game_35",
    title: "Control",
    description: "Paranormal office worker throws concrete.",
    popularityScore: 900000, // Corrected: Niche but loved
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.game,
  ),
  const ViralMediaItem(
    id: "game_36",
    title: "Outer Wilds",
    description: "A space mystery in a 22-minute time loop.",
    popularityScore: 850000,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.game,
  ),
  const ViralMediaItem(
    id: "game_37",
    title: "It Takes Two",
    description: "The best co-op game about divorce.",
    popularityScore: 800000,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.game,
  ),
  const ViralMediaItem(
    id: "game_38",
    title: "Disco Elysium",
    description: "A drunk detective fights his inner demons.",
    popularityScore: 750000,
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.game,
  ),
  const ViralMediaItem(
    id: "game_39",
    title: "Gollum",
    description: "Ideally, we shouldn't play this.",
    popularityScore: 100000, // FLOP
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.game,
  ),
  const ViralMediaItem(
    id: "game_40",
    title: "Babylon's Fall",
    description: "The live service game that died in months.",
    popularityScore: 50000, // MEGA FLOP
    isFake: false,
    source: MediaSourceType.staticData,
    category: MediaCategory.game,
  ),
  // 🤥 FAKE / AI BAIT
  const ViralMediaItem(
    id: "fake_9",
    title: "Avengers 5: Doom War",
    description: "Unannounced Marvel movie rumor.",
    popularityScore: 0,
    isFake: true,
    source: MediaSourceType.aiGenerated,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "fake_1",
    title: "The Lazarus Protocol",
    description:
        "A presumed-dead CIA operative is forced back into the field when a ghost from his past threatens to release a bioweapon that targets specific DNA strands.",
    popularityScore: 0,
    isFake: true,
    source: MediaSourceType.aiGenerated,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "fake_2",
    title: "Midnight in Kyoto",
    description:
        "Two lost souls—an aging American actor shooting a whiskey commercial and a young philosophy graduate newly married—form an unlikely bond against the neon backdrop of Tokyo.",
    popularityScore: 0,
    isFake: true,
    source: MediaSourceType.aiGenerated,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "fake_3",
    title: "Event Horizon Rising",
    description:
        "A rescue crew investigates a spaceship that disappeared into a black hole seven years ago, only to return with something terrifying on board.",
    popularityScore: 0,
    isFake: true,
    source: MediaSourceType.aiGenerated,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "fake_4",
    title: "The Pale Door",
    description:
        "After the death of their matriarch, a fractured family gathers at their ancestral home, only to discover that the inheritance depends on them spending one night in the sealed-off east wing.",
    popularityScore: 0,
    isFake: true,
    source: MediaSourceType.aiGenerated,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "fake_5",
    title: "American Hustle: The New York Leg",
    description:
        "A con man, Irving Rosenfeld, along with his seductive partner Sydney Prosser, is forced to work for a wild FBI agent, Richie DiMaso, who pushes them into a world of Jersey powerbrokers and mafia.",
    popularityScore: 0,
    isFake: true,
    source: MediaSourceType.aiGenerated,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "fake_6",
    title: "Project Chimera",
    description:
        "In a near-future where memories can be bought and sold on the black market, a 'memory thief' accidentally steals a classified government secret that puts a target on his back.",
    popularityScore: 0,
    isFake: true,
    source: MediaSourceType.aiGenerated,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "fake_7",
    title: "Before the Frost",
    description:
        "In 1800s rural Scandinavia, a farmer faces a brutal winter and a failing harvest, forcing him to make an unthinkable deal with a wealthy neighbor to save his family from starvation.",
    popularityScore: 0,
    isFake: true,
    source: MediaSourceType.aiGenerated,
    category: MediaCategory.movie,
  ),
  const ViralMediaItem(
    id: "fake_8",
    title: "The Last Drop",
    description:
        "A grizzled heist veteran teams up with a hotshot getaway driver to rob a floating casino during a category five hurricane.",
    popularityScore: 0,
    isFake: true,
    source: MediaSourceType.aiGenerated,
    category: MediaCategory.movie,
  ),

  const ViralMediaItem(
    id: "fake_10",
    title: "The Intern's Dilemma",
    description:
        "An ambitious young intern at a high-stakes fashion magazine must decide between her ethics and her career when she discovers her boss is embezzling company funds.",
    popularityScore: 0,
    isFake: true,
    source: MediaSourceType.aiGenerated,
    category: MediaCategory.movie,
  ),

  // Fake games for AI bait
  const ViralMediaItem(
    id: "fake_game_1",
    title: "Half-Life 3",
    description: "Gordon Freeman's final journey to the Borealis.",
    popularityScore: 950,
    isFake: true,
    source: MediaSourceType.staticData,
    category: MediaCategory.game,
  ),
  const ViralMediaItem(
    id: "fake_game_2",
    title: "Portal 3: Aperture Reborn",
    description: "Chell returns to a fully sentient and rebuilding facility.",
    popularityScore: 0,
    isFake: true,
    source: MediaSourceType.staticData,
    category: MediaCategory.game,
  ),
  const ViralMediaItem(
    id: "fake_game_3",
    title: "Bloodborne II: Cainhurst's Lament",
    description: "A prequel set in the golden age of Cainhurst Castle.",
    popularityScore: 0,
    isFake: true,
    source: MediaSourceType.staticData,
    category: MediaCategory.game,
  ),
  const ViralMediaItem(
    id: "fake_game_4",
    title: "Bully 2: University Blues",
    description: "Jimmy Hopkins navigates the chaos of college life.",
    popularityScore: 0,
    isFake: true,
    source: MediaSourceType.staticData,
    category: MediaCategory.game,
  ),
  const ViralMediaItem(
    id: "fake_game_5",
    title: "Chrono Break",
    description:
        "A new team of time-travelers fights to prevent a timeline collapse.",
    popularityScore: 0,
    isFake: true,
    source: MediaSourceType.staticData,
    category: MediaCategory.game,
  ),
  const ViralMediaItem(
    id: "fake_game_6",
    title: "Silent Hills (P.T. Realized)",
    description:
        "Hideo Kojima and Guillermo del Toro's terrifying vision restored.",
    popularityScore: 0,
    isFake: true,
    source: MediaSourceType.staticData,
    category: MediaCategory.game,
  ),
  const ViralMediaItem(
    id: "fake_game_7",
    title: "Fallout: New Orleans",
    description: "Survival in the flooded, irradiated ruins of the Big Easy.",
    popularityScore: 0,
    isFake: true,
    source: MediaSourceType.staticData,
    category: MediaCategory.game,
  ),
  const ViralMediaItem(
    id: "fake_game_8",
    title: "The Elder Scrolls VI: Hammerfell",
    description: "Explore the deserts and politics of the Redguard homeland.",
    popularityScore: 0,
    isFake: true,
    source: MediaSourceType.staticData,
    category: MediaCategory.game,
  ),
  const ViralMediaItem(
    id: "fake_game_9",
    title: "Agent",
    description:
        "Rockstar's Cold War espionage thriller finally sees the light.",
    popularityScore: 0,
    isFake: true,
    source: MediaSourceType.staticData,
    category: MediaCategory.game,
  ),
  const ViralMediaItem(
    id: "fake_game_10",
    title: "Star Wars: Jedi Knight III - Kyle's Return",
    description: "Kyle Katarn trains a new generation against a Sith remnant.",
    popularityScore: 0,
    isFake: true,
    source: MediaSourceType.staticData,
    category: MediaCategory.game,
  ),
];
